### ISSUE TITLE
(Peer feedback) Update report to clarify what data was used in analysis vs EDA and to include what years were covered in data set

### ISSUE THREAD

**Issue by carrieklc** [UBC-MDS/DSCI_522-Chocolate_Ratings_Analysis#24]
@rachelkriggs Received peer feedback to update 2 things in the final report:
1) Clarify that data removed in exploratory analysis plot was not removed in the actual analysis
2) State what range of years the data set ratings cover

We also received feedback that there could be other variables in the data set which influence chocolate ratings (e.g. cocoa percentage). In response, we understand this is certainly possible however those variables were not the focus of our specific question and hypothesis test.

**Comment by rachelkriggs** [comment]
Changes look good to me so I'm closing this issue.

**Comment by carrieklc** [comment]
Addressed by commit edd3f9b2047dc1f9fa792fc8d3ed8b98e1a4356d
