### ISSUE TITLE
Add how to use Makefile in suggested usage

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522-Chocolate_Ratings_Analysis#31]
Given that you know have a Makefile I suggest you add how to use Makefile in suggested Usage section.

**Comment by rachelkriggs** [comment]
@ttimbers @carrieklc   Is it okay to replace the existing usage (running each script separately) with this, or should it be in addition, as an alternative (as the Docker usage is)?

**Comment by ttimbers** [comment]
> should it be in addition, as an alternative (as the Docker usage is)?

I think that is best.

**Comment by carrieklc** [comment]
We've added it as an additional usage option in our README at ca8823b5e89cb29ff1568fa816318b808ed524c4

Thanks!
