### ISSUE TITLE
`all` target could be simplified?

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522-Chocolate_Ratings_Analysis#35]
https://github.com/UBC-MDS/DSCI_522-Chocolate_Ratings_Analysis/blob/92745239220c596428681ba9d46e6df1c83aeac1/Makefile#L14

Your `all` target could be simplified I think. It might only need to be `doc/Report.md` since everything else is a dependency of that.

**Comment by carrieklc** [comment]
Thank you for pointing this out, Tiffany. 
We've made the change in ca8823b5e89cb29ff1568fa816318b808ed524c4
