### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522-Chocolate_Ratings_Analysis#9]
__Mechanics__

* Since README is the landing page of your project, you might want to replace the standard repo name to a more meaningful project title for a more polished and professional look and feel. 

* In your proposal, the link to v0.1 points to the release page. It would be nice to have a link directly to v0.1 of the repo, i.e. https://github.com/UBC-MDS/DSCI_522-rriggs-ccheung/tree/v0.1. 3. 

* For directory structure, assuming that results/ will be for intermediate outputs from your R or Python script, you might want to create a doc/ folder for the final reports or summaries. See example structure from Tiffany on Slack at Nov 16 14:54.

* (Optional) might want to show a snapshot of the imported data with an R snippet in the markdown file of README. Not sure if you can do this with GitHub... 

__Reasoning__

* Could have clarify a little more on the proposed visualizations, especially for the 2nd sentence. I suppose by 'null distribution', you are referring to the distribution of the test statistics from the simulation or randomly permuted data; yet the scales of the test statistics, the p-values and the confidence intervals of the ratings (or difference in ratings) are all different. It is unclear how you can overlay all three in a single plot easily.

**Comment by carrieklc** [comment]
Hi Eric,

Thank you for the feedback. Below is a summary of how we've addressed each item of feedback:

|Feedback| Action|
|--------|-------|
|Mechanics 1: Rename repo with more meaningful title| Renamed repo from DSCI_522-rriggs-ccheung to DSCI_522-Chocolate_Ratings_Analysis|
|Mechanics 2: Link directly to release| We will include a link in our milestone1 repo to directly point to the release. |
|Mechanics 3: Update directory structure|f4c80a6fca9436ed57a4a4eddd5c08887c4b0f09|
|Mechanics 4 (optional): Show snapshot of imported data.| We could not do this an R snippet in markdown on GitHub, however we have included an embedded image of the first few rows of the dataset: 2df1f9e4eb63f8e72579da565e67c4d878c8f0b8|
|Reasoning: Clarify explanation of visualizations| Yes, by 'null distribution', we do mean the distribution of the test statistics from permutation. Please see our report for the final visualizations: https://github.com/UBC-MDS/DSCI_522-Chocolate_Ratings_Analysis/blob/master/doc/Report.md |
